### ISSUE TITLE
Trouble with RSA 2048 cert signing

### ISSUE THREAD

**Issue by hongkongkiwi** [JackOfMostTrades/aws-kms-pkcs11#9]
I've been successfully using ECC keys for signing, but now I need to create a root rsa CA. I've created a 2048 KMS RSA key.

I'm using the following line:
```
export CONFIG="
[req]
distinguished_name=dn
[ dn ]
"
export PKCS11_MODULE_PATH=/usr/lib/x86_64-linux-gnu/pkcs11/aws_kms_pkcs11.so
openssl req -x509 -config <(echo "$CONFIG") -key "pkcs11:token=root-ca-rsa" -engine pkcs11 -keyform engine -out /tmp/root-ca-rsa.pem -days 36500 -subj "/C=US/ST=Test/L=Test/O=Test/OU=Test/CN=My CA/emailAddress=me@me.com/" -addext basicConstraints=critical,CA:TRUE
```

```
engine "pkcs11" set.
AWS_KMS: Debug enabled.
AWS_KMS: Attempting to load config from path: /root/.config/aws-kms-pkcs11/config.json
AWS_KMS: Skipping config because we couldn't open the file.
AWS_KMS: Attempting to load config from path: /etc/aws-kms-pkcs11/config.json
AWS_KMS: Configured slots:
AWS_KMS:   fa86ae01-9c74-4156-8b1a-721a589580d2
AWS_KMS: Getting public key for key fa86ae01-9c74-4156-8b1a-721a589580d2
AWS_KMS: Successfully fetched public key data.
AWS_KMS: Error signing: Digest is invalid length for algorithm RSASSA_PKCS1_V1_5_SHA_256.
139878421697856:error:8207A006:PKCS#11 module:pkcs11_private_encrypt:Function failed:p11_rsa.c:116:
139878421697856:error:0D0DC006:asn1 encoding routines:ASN1_item_sign_ctx:EVP lib:../crypto/asn1/a_sign.c:224:
```

I can successfully perform a signing operation using openssl debug (as we've used before).

**Comment by hongkongkiwi** [comment]
Is it because we are not adding the correct  PKCS #1v1.5 Padding?

**Comment by JackOfMostTrades** [comment]
Heh, shows you how much testing I did with RSA rather than EC. ;) The way RSA PKCS #1v1.5 works, it's expected that the digest is prefixed with some ASN.1 that identifies the hashing algorithm. This is done _outside_ of PKCS11 providers since just the raw bytes are passed into the PKCS11 module for signing. But KMS prepends this itself when doing signing, so the module basically just needs to strip this off.

I've kept things simple for myself and am just supporting SHA-256, but with that caveat commit 7271069 should fix this.

**Comment by hongkongkiwi** [comment]
Thanks for looking into it. RSA is not my first choice, but unfortunately uboot signing only supports RSA so I have to use that as well.

With the latest master and a fresh compile I'm still getting the same error:
```
AWS_KMS: Error signing: Digest is invalid length for algorithm RSASSA_PKCS1_V1_5_SHA_256.
140585579668800:error:8207A006:PKCS#11 module:pkcs11_private_encrypt:Function failed:p11_rsa.c:116:
140585579668800:error:0D0DC006:asn1 encoding routines:ASN1_item_sign_ctx:EVP lib:../crypto/asn1/a_sign.c:224:
```

**Comment by hongkongkiwi** [comment]
Thanks for the fix! It looks like it's fixed now, I'm only using sha256 as well. I'll continue the testing with my usecases :)
